In [1]:
import pdb

from pandas._libs.tslibs.offsets import Nano

from data_manager.jobs import data_engineer
from data_manager.storage.csv_backend import CSVStorage
from data_manager.jobs.data_engineer import DataEngineer

In [2]:
import pandas as pd
import numpy as np

np.random.seed(42)

# Create base dataframe
df = pd.DataFrame({
    "id": np.arange(1, 51),
    "name": np.random.choice(
        ["Alice", "Bob", "Charlie", "David", "Eva", None],
        50
    ),
    "age": np.random.choice(
        [22, 25, 28, 31, 35, np.nan],
        50
    ),
    "salary": np.random.choice(
        [45000, 55000, 65000, 75000, np.nan],
        50
    ),
    "department": np.random.choice(
        ["HR", "IT", "Finance", "Sales", None],
        50
    ),
    "city": np.random.choice(
        ["Delhi", "Mumbai", "Pune", "Bangalore", None],
        50
    ),
    "rating": np.random.choice(
        [1, 2, 3, 4, 5, np.nan],
        50
    ),
    "experience": np.random.choice(
        [1, 3, 5, 7, 10, np.nan],
        50
    ),
    "status": np.random.choice(
        ["Active", "Inactive", None],
        50
    ),
    "score": np.random.choice(
        [55.5, 67.8, 72.1, 88.4, 91.2, np.nan],
        50
    )
})

# Introduce duplicate rows
df.iloc[10] = df.iloc[0]
df.iloc[20] = df.iloc[5]
df.iloc[30] = df.iloc[10]

print(df)

print("\nShape:", df.shape)
print("\nDuplicate Rows:")
print(df[df.duplicated()])

print("\nNull Values Count:")
print(df.isnull().sum())

    id     name   age   salary department       city  rating  experience  \
0    1    David   NaN      NaN        NaN     Mumbai     4.0         5.0
1    2      Eva  25.0  45000.0    Finance     Mumbai     1.0         NaN
2    3  Charlie  25.0  45000.0    Finance  Bangalore     2.0         NaN
3    4      Eva  22.0  45000.0      Sales        NaN     1.0         NaN
4    5      Eva  25.0  45000.0         IT      Delhi     NaN         NaN
5    6      Bob  35.0  75000.0         IT      Delhi     4.0         NaN
6    7  Charlie  25.0  65000.0        NaN       Pune     5.0         NaN
7    8  Charlie  31.0  65000.0         HR     Mumbai     5.0        10.0
8    9  Charlie  31.0  45000.0        NaN        NaN     3.0         5.0
9   10      Eva  31.0  65000.0      Sales  Bangalore     1.0         NaN
10   1    David   NaN      NaN        NaN     Mumbai     4.0         5.0
11  12  Charlie  35.0  45000.0      Sales  Bangalore     3.0         5.0
12  13      NaN  28.0  65000.0      Sales       Pune     3.0         3.0
13  14      Eva   NaN      NaN      Sales       Pune     3.0        10.0
14  15      Bob  22.0  55000.0    Finance      Delhi     4.0         NaN
15  16    David  31.0  55000.0         IT        NaN     NaN         1.0
16  17      NaN  25.0  45000.0      Sales  Bangalore     1.0         7.0
17  18      NaN  31.0  75000.0         HR     Mumbai     4.0         1.0
18  19      Bob  25.0  45000.0         HR       Pune     3.0        10.0
19  20    David   NaN  75000.0         HR      Delhi     1.0         7.0
20   6      Bob  35.0  75000.0         IT      Delhi     4.0         NaN
21  22    Alice   NaN  45000.0    Finance  Bangalore     NaN         5.0
22  23    David  25.0      NaN         HR       Pune     4.0         7.0
23  24      Bob  31.0  65000.0      Sales        NaN     NaN         5.0
24  25      NaN   NaN  75000.0        NaN       Pune     3.0         1.0
25  26      Eva  35.0  65000.0         HR  Bangalore     NaN         1.0
26  27    David  25.0  65000.0    Finance  Bangalore     1.0         7.0
27  28    Alice  25.0  45000.0    Finance       Pune     3.0         7.0
28  29    Alice  31.0  65000.0         HR  Bangalore     1.0         NaN
29  30  Charlie  25.0      NaN        NaN       Pune     5.0        10.0
30   1    David   NaN      NaN        NaN     Mumbai     4.0         5.0
31  32      Bob   NaN  45000.0    Finance       Pune     NaN        10.0
32  33    David  31.0      NaN         IT       Pune     2.0         NaN
33  34    David   NaN  55000.0      Sales  Bangalore     2.0         5.0
34  35      NaN   NaN  65000.0    Finance  Bangalore     NaN         7.0
35  36      NaN  31.0  45000.0         HR      Delhi     3.0         1.0
36  37      NaN  22.0  55000.0      Sales      Delhi     5.0        10.0
37  38  Charlie   NaN  55000.0         HR     Mumbai     1.0        10.0
38  39    David  35.0  75000.0         HR      Delhi     4.0         1.0
39  40    David  35.0      NaN         IT       Pune     1.0         NaN
40  41    Alice  25.0  65000.0      Sales  Bangalore     4.0        10.0
41  42  Charlie  35.0  45000.0      Sales      Delhi     1.0         5.0
42  43      Eva  25.0  75000.0         IT      Delhi     NaN         7.0
43  44  Charlie  22.0      NaN    Finance     Mumbai     5.0         1.0
44  45      Eva  31.0  75000.0         HR     Mumbai     4.0         7.0
45  46    Alice  31.0      NaN        NaN       Pune     3.0        10.0
46  47      Bob  31.0      NaN         HR  Bangalore     1.0        10.0
47  48    David  35.0  65000.0         HR     Mumbai     1.0         1.0
48  49    Alice  22.0      NaN    Finance      Delhi     4.0         5.0
49  50    David  35.0  75000.0         HR  Bangalore     3.0         3.0

      status  score
0     Active    NaN
1   Inactive   91.2
2        NaN    NaN
3   Inactive   67.8
4   Inactive   67.8
5        NaN    NaN
6   Inactive   55.5
7   Inactive   88.4
8        NaN   67.8
9   Inactive    NaN
10    Active    NaN
11  Inactive   72.1
12       NaN   88.4
13       NaN   91.2
14  Inactive   55.5
15  Inactive   91.2
16  Inactive   88.4
17    Active   88.4
18    Active   88.4
19    Active   91.2
20       NaN    NaN
21  Inactive    NaN
22       NaN   91.2
23    Active   88.4
24  Inactive    NaN
25       NaN   72.1
26  Inactive   88.4
27       NaN   91.2
28  Inactive   67.8
29    Active   88.4
30    Active    NaN
31  Inactive    NaN
32       NaN   72.1
33    Active   55.5
34    Active   72.1
35    Active   88.4
36  Inactive   67.8
37  Inactive   67.8
38       NaN   91.2
39       NaN   67.8
40       NaN   91.2
41  Inactive    NaN
42  Inactive   55.5
43       NaN   88.4
44       NaN   91.2
45  Inactive   55.5
46       NaN   67.8
47    Active   67.8
48  Inactive   55.5
49       NaN   67.8

Shape: (50, 10)

Duplicate Rows:
    id   name   age   salary department    city  rating  experience  status  \
10   1  David   NaN      NaN        NaN  Mumbai     4.0         5.0  Active
20   6    Bob  35.0  75000.0         IT   Delhi     4.0         NaN     NaN
30   1  David   NaN      NaN        NaN  Mumbai     4.0         5.0  Active

    score
10    NaN
20    NaN
30    NaN

Null Values Count:
id             0
name           7
age           11
salary        12
department     8
city           4
rating         8
experience    12
status        17
score         11
dtype: int64

In [5]:
df.to_csv("D:\\workspace\\Dev tools\\PythonProjects\\DataManager\\tests\\Data\\test_data_1.csv", index=False)

In [4]:
data_manager = CSVStorage()
test_data_path = "D:\\workspace\\Dev tools\\PythonProjects\\DataManager\\tests\\Data\\test_data_1.csv"
data_manager.load(test_data_path)

In [10]:
data_manager.dd

,Unnamed: 0,id,name,age,salary,department,city,rating,experience,status,score
7,7,8,Charlie,31.0,65000.0,HR,Mumbai,5.0,10.0,Inactive,88.4
11,11,12,Charlie,35.0,45000.0,Sales,Bangalore,3.0,5.0,Inactive,72.1
18,18,19,Bob,25.0,45000.0,HR,Pune,3.0,10.0,Active,88.4
26,26,27,David,25.0,65000.0,Finance,Bangalore,1.0,7.0,Inactive,88.4
47,47,48,David,35.0,65000.0,HR,Mumbai,1.0,1.0,Active,67.8

In [6]:
data_engineer_job = DataEngineer(data_manager)

In [7]:
data_engineer_tasks = [
    {
        "function": "removeDublicate",
        "params": {}
    },
    {
        "function": "removeNull",
        "params": {
            "method" : "drop"
        }
    }
]

In [8]:
data_engineer_job.run(data_engineer_tasks)

In [9]:
data_manager.dd

,Unnamed: 0,id,name,age,salary,department,city,rating,experience,status,score
7,7,8,Charlie,31.0,65000.0,HR,Mumbai,5.0,10.0,Inactive,88.4
11,11,12,Charlie,35.0,45000.0,Sales,Bangalore,3.0,5.0,Inactive,72.1
18,18,19,Bob,25.0,45000.0,HR,Pune,3.0,10.0,Active,88.4
26,26,27,David,25.0,65000.0,Finance,Bangalore,1.0,7.0,Inactive,88.4
47,47,48,David,35.0,65000.0,HR,Mumbai,1.0,1.0,Active,67.8