In [2]:
import json

import pandas as pd
from IPython.core import display_functions

In [3]:
test_data_path = "D:\\workspace\\Dev tools\\PythonProjects\\DataManager\\tests\\Data\\test_data_1.csv"

In [9]:
df = pd.read_csv(test_data_path)

df

,Unnamed: 0,id,name,age,salary,department,city,rating,experience,status,score
0,0,1,David,NaN,NaN,NaN,Mumbai,4.0,5.0,Active,NaN
1,1,2,Eva,25.0,45000.0,Finance,Mumbai,1.0,NaN,Inactive,91.2
2,2,3,Charlie,25.0,45000.0,Finance,Bangalore,2.0,NaN,NaN,NaN
3,3,4,Eva,22.0,45000.0,Sales,NaN,1.0,NaN,Inactive,67.8
4,4,5,Eva,25.0,45000.0,IT,Delhi,NaN,NaN,Inactive,67.8
5,5,6,Bob,35.0,75000.0,IT,Delhi,4.0,NaN,NaN,NaN
6,6,7,Charlie,25.0,65000.0,NaN,Pune,5.0,NaN,Inactive,55.5
7,7,8,Charlie,31.0,65000.0,HR,Mumbai,5.0,10.0,Inactive,88.4
8,8,9,Charlie,31.0,45000.0,NaN,NaN,3.0,5.0,NaN,67.8
9,9,10,Eva,31.0,65000.0,Sales,Bangalore,1.0,NaN,Inactive,NaN
10,10,1,David,NaN,NaN,NaN,Mumbai,4.0,5.0,Active,NaN
11,11,12,Charlie,35.0,45000.0,Sales,Bangalore,3.0,5.0,Inactive,72.1
12,12,13,NaN,28.0,65000.0,Sales,Pune,3.0,3.0,NaN,88.4
13,13,14,Eva,NaN,NaN,Sales,Pune,3.0,10.0,NaN,91.2
14,14,15,Bob,22.0,55000.0,Finance,Delhi,4.0,NaN,Inactive,55.5
15,15,16,David,31.0,55000.0,IT,NaN,NaN,1.0,Inactive,91.2
16,16,17,NaN,25.0,45000.0,Sales,Bangalore,1.0,7.0,Inactive,88.4
17,17,18,NaN,31.0,75000.0,HR,Mumbai,4.0,1.0,Active,88.4
18,18,19,Bob,25.0,45000.0,HR,Pune,3.0,10.0,Active,88.4
19,19,20,David,NaN,75000.0,HR,Delhi,1.0,7.0,Active,91.2
20,20,6,Bob,35.0,75000.0,IT,Delhi,4.0,NaN,NaN,NaN
21,21,22,Alice,NaN,45000.0,Finance,Bangalore,NaN,5.0,Inactive,NaN
22,22,23,David,25.0,NaN,HR,Pune,4.0,7.0,NaN,91.2
23,23,24,Bob,31.0,65000.0,Sales,NaN,NaN,5.0,Active,88.4
24,24,25,NaN,NaN,75000.0,NaN,Pune,3.0,1.0,Inactive,NaN
25,25,26,Eva,35.0,65000.0,HR,Bangalore,NaN,1.0,NaN,72.1
26,26,27,David,25.0,65000.0,Finance,Bangalore,1.0,7.0,Inactive,88.4
27,27,28,Alice,25.0,45000.0,Finance,Pune,3.0,7.0,NaN,91.2
28,28,29,Alice,31.0,65000.0,HR,Bangalore,1.0,NaN,Inactive,67.8
29,29,30,Charlie,25.0,NaN,NaN,Pune,5.0,10.0,Active,88.4
30,30,1,David,NaN,NaN,NaN,Mumbai,4.0,5.0,Active,NaN
31,31,32,Bob,NaN,45000.0,Finance,Pune,NaN,10.0,Inactive,NaN
32,32,33,David,31.0,NaN,IT,Pune,2.0,NaN,NaN,72.1
33,33,34,David,NaN,55000.0,Sales,Bangalore,2.0,5.0,Active,55.5
34,34,35,NaN,NaN,65000.0,Finance,Bangalore,NaN,7.0,Active,72.1
35,35,36,NaN,31.0,45000.0,HR,Delhi,3.0,1.0,Active,88.4
36,36,37,NaN,22.0,55000.0,Sales,Delhi,5.0,10.0,Inactive,67.8
37,37,38,Charlie,NaN,55000.0,HR,Mumbai,1.0,10.0,Inactive,67.8
38,38,39,David,35.0,75000.0,HR,Delhi,4.0,1.0,NaN,91.2
39,39,40,David,35.0,NaN,IT,Pune,1.0,NaN,NaN,67.8
40,40,41,Alice,25.0,65000.0,Sales,Bangalore,4.0,10.0,NaN,91.2
41,41,42,Charlie,35.0,45000.0,Sales,Delhi,1.0,5.0,Inactive,NaN
42,42,43,Eva,25.0,75000.0,IT,Delhi,NaN,7.0,Inactive,55.5
43,43,44,Charlie,22.0,NaN,Finance,Mumbai,5.0,1.0,NaN,88.4
44,44,45,Eva,31.0,75000.0,HR,Mumbai,4.0,7.0,NaN,91.2
45,45,46,Alice,31.0,NaN,NaN,Pune,3.0,10.0,Inactive,55.5
46,46,47,Bob,31.0,NaN,HR,Bangalore,1.0,10.0,NaN,67.8
47,47,48,David,35.0,65000.0,HR,Mumbai,1.0,1.0,Active,67.8
48,48,49,Alice,22.0,NaN,Finance,Delhi,4.0,5.0,Inactive,55.5
49,49,50,David,35.0,75000.0,HR,Bangalore,3.0,3.0,NaN,67.8

In [8]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 10 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   id          50 non-null     int64
 1   name        43 non-null     str
 2   age         39 non-null     float64
 3   salary      38 non-null     float64
 4   department  42 non-null     str
 5   city        46 non-null     str
 6   rating      42 non-null     float64
 7   experience  38 non-null     float64
 8   status      33 non-null     str
 9   score       39 non-null     float64
dtypes: float64(5), int64(1), str(4)
memory usage: 4.0 KB

In [41]:
details = df.describe()
details

              id        age        salary     rating  experience      score
count  50.000000  39.000000     38.000000  42.000000   38.000000  39.000000
mean   24.400000  28.846154  59210.526316   2.880952    5.789474  77.030769
std    15.433862   4.614271  11998.103217   1.417700    3.264534  13.406855
min     1.000000  22.000000  45000.000000   1.000000    1.000000  55.500000
25%    10.500000  25.000000  45000.000000   1.000000    3.500000  67.800000
50%    24.500000  31.000000  65000.000000   3.000000    5.000000  72.100000
75%    37.750000  31.000000  65000.000000   4.000000    9.250000  88.400000
max    50.000000  35.000000  75000.000000   5.000000   10.000000  91.200000

In [24]:
details.iloc[:,0].values

array([50.        , 24.4       , 15.43386153,  1.        , 10.5       ,
       24.5       , 37.75      , 50.        ])

In [25]:
details.iloc[:,0].keys()

Index(['count', 'mean', 'std', 'min', '25%', '50%', '75%', 'max'], dtype='str')

In [31]:
map = details.iloc[:,0].to_json()

In [40]:
map = json.loads(map)
map

{'count': 50.0,
 'mean': 24.4,
 'std': 15.4338615269,
 'min': 1.0,
 '25%': 10.5,
 '50%': 24.5,
 '75%': 37.75,
 'max': 50.0}

In [7]:
df.iloc[:,1:].isnull().sum()

name           7
age           11
salary        12
department     8
city           4
rating         8
experience    12
status        17
score         11
dtype: int64

In [10]:
missing_dict = df.isnull().sum().to_dict()
missing_dict

{'Unnamed: 0': 0,
 'id': 0,
 'name': 7,
 'age': 11,
 'salary': 12,
 'department': 8,
 'city': 4,
 'rating': 8,
 'experience': 12,
 'status': 17,
 'score': 11}