In [1]:
import json
from msilib import schema

import pandas as pd
from IPython.core import display_functions

In [2]:
test_data_path = "D:\\workspace\\Dev tools\\PythonProjects\\DataManager\\tests\\Data\\test_data_1.csv"

In [3]:
df = pd.read_csv(test_data_path)

df

,id,name,age,salary,department,city,rating,experience,status,score
0,1,David,NaN,NaN,NaN,Mumbai,4.0,5.0,Active,NaN
1,2,Eva,25.0,45000.0,Finance,Mumbai,1.0,NaN,Inactive,91.2
2,3,Charlie,25.0,45000.0,Finance,Bangalore,2.0,NaN,NaN,NaN
3,4,Eva,22.0,45000.0,Sales,NaN,1.0,NaN,Inactive,67.8
4,5,Eva,25.0,45000.0,IT,Delhi,NaN,NaN,Inactive,67.8
5,6,Bob,35.0,75000.0,IT,Delhi,4.0,NaN,NaN,NaN
6,7,Charlie,25.0,65000.0,NaN,Pune,5.0,NaN,Inactive,55.5
7,8,Charlie,31.0,65000.0,HR,Mumbai,5.0,10.0,Inactive,88.4
8,9,Charlie,31.0,45000.0,NaN,NaN,3.0,5.0,NaN,67.8
9,10,Eva,31.0,65000.0,Sales,Bangalore,1.0,NaN,Inactive,NaN
10,1,David,NaN,NaN,NaN,Mumbai,4.0,5.0,Active,NaN
11,12,Charlie,35.0,45000.0,Sales,Bangalore,3.0,5.0,Inactive,72.1
12,13,NaN,28.0,65000.0,Sales,Pune,3.0,3.0,NaN,88.4
13,14,Eva,NaN,NaN,Sales,Pune,3.0,10.0,NaN,91.2
14,15,Bob,22.0,55000.0,Finance,Delhi,4.0,NaN,Inactive,55.5
15,16,David,31.0,55000.0,IT,NaN,NaN,1.0,Inactive,91.2
16,17,NaN,25.0,45000.0,Sales,Bangalore,1.0,7.0,Inactive,88.4
17,18,NaN,31.0,75000.0,HR,Mumbai,4.0,1.0,Active,88.4
18,19,Bob,25.0,45000.0,HR,Pune,3.0,10.0,Active,88.4
19,20,David,NaN,75000.0,HR,Delhi,1.0,7.0,Active,91.2
20,6,Bob,35.0,75000.0,IT,Delhi,4.0,NaN,NaN,NaN
21,22,Alice,NaN,45000.0,Finance,Bangalore,NaN,5.0,Inactive,NaN
22,23,David,25.0,NaN,HR,Pune,4.0,7.0,NaN,91.2
23,24,Bob,31.0,65000.0,Sales,NaN,NaN,5.0,Active,88.4
24,25,NaN,NaN,75000.0,NaN,Pune,3.0,1.0,Inactive,NaN
25,26,Eva,35.0,65000.0,HR,Bangalore,NaN,1.0,NaN,72.1
26,27,David,25.0,65000.0,Finance,Bangalore,1.0,7.0,Inactive,88.4
27,28,Alice,25.0,45000.0,Finance,Pune,3.0,7.0,NaN,91.2
28,29,Alice,31.0,65000.0,HR,Bangalore,1.0,NaN,Inactive,67.8
29,30,Charlie,25.0,NaN,NaN,Pune,5.0,10.0,Active,88.4
30,1,David,NaN,NaN,NaN,Mumbai,4.0,5.0,Active,NaN
31,32,Bob,NaN,45000.0,Finance,Pune,NaN,10.0,Inactive,NaN
32,33,David,31.0,NaN,IT,Pune,2.0,NaN,NaN,72.1
33,34,David,NaN,55000.0,Sales,Bangalore,2.0,5.0,Active,55.5
34,35,NaN,NaN,65000.0,Finance,Bangalore,NaN,7.0,Active,72.1
35,36,NaN,31.0,45000.0,HR,Delhi,3.0,1.0,Active,88.4
36,37,NaN,22.0,55000.0,Sales,Delhi,5.0,10.0,Inactive,67.8
37,38,Charlie,NaN,55000.0,HR,Mumbai,1.0,10.0,Inactive,67.8
38,39,David,35.0,75000.0,HR,Delhi,4.0,1.0,NaN,91.2
39,40,David,35.0,NaN,IT,Pune,1.0,NaN,NaN,67.8
40,41,Alice,25.0,65000.0,Sales,Bangalore,4.0,10.0,NaN,91.2
41,42,Charlie,35.0,45000.0,Sales,Delhi,1.0,5.0,Inactive,NaN
42,43,Eva,25.0,75000.0,IT,Delhi,NaN,7.0,Inactive,55.5
43,44,Charlie,22.0,NaN,Finance,Mumbai,5.0,1.0,NaN,88.4
44,45,Eva,31.0,75000.0,HR,Mumbai,4.0,7.0,NaN,91.2
45,46,Alice,31.0,NaN,NaN,Pune,3.0,10.0,Inactive,55.5
46,47,Bob,31.0,NaN,HR,Bangalore,1.0,10.0,NaN,67.8
47,48,David,35.0,65000.0,HR,Mumbai,1.0,1.0,Active,67.8
48,49,Alice,22.0,NaN,Finance,Delhi,4.0,5.0,Inactive,55.5
49,50,David,35.0,75000.0,HR,Bangalore,3.0,3.0,NaN,67.8

In [8]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 10 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   id          50 non-null     int64
 1   name        43 non-null     str
 2   age         39 non-null     float64
 3   salary      38 non-null     float64
 4   department  42 non-null     str
 5   city        46 non-null     str
 6   rating      42 non-null     float64
 7   experience  38 non-null     float64
 8   status      33 non-null     str
 9   score       39 non-null     float64
dtypes: float64(5), int64(1), str(4)
memory usage: 4.0 KB

In [41]:
details = df.describe()
details

              id        age        salary     rating  experience      score
count  50.000000  39.000000     38.000000  42.000000   38.000000  39.000000
mean   24.400000  28.846154  59210.526316   2.880952    5.789474  77.030769
std    15.433862   4.614271  11998.103217   1.417700    3.264534  13.406855
min     1.000000  22.000000  45000.000000   1.000000    1.000000  55.500000
25%    10.500000  25.000000  45000.000000   1.000000    3.500000  67.800000
50%    24.500000  31.000000  65000.000000   3.000000    5.000000  72.100000
75%    37.750000  31.000000  65000.000000   4.000000    9.250000  88.400000
max    50.000000  35.000000  75000.000000   5.000000   10.000000  91.200000

In [24]:
details.iloc[:,0].values

array([50.        , 24.4       , 15.43386153,  1.        , 10.5       ,
       24.5       , 37.75      , 50.        ])

In [25]:
details.iloc[:,0].keys()

Index(['count', 'mean', 'std', 'min', '25%', '50%', '75%', 'max'], dtype='str')

In [31]:
map = details.iloc[:,0].to_json()

In [40]:
map = json.loads(map)
map

{'count': 50.0,
 'mean': 24.4,
 'std': 15.4338615269,
 'min': 1.0,
 '25%': 10.5,
 '50%': 24.5,
 '75%': 37.75,
 'max': 50.0}

In [7]:
df.iloc[:,1:].isnull().sum()

name           7
age           11
salary        12
department     8
city           4
rating         8
experience    12
status        17
score         11
dtype: int64

In [11]:
missing_dict = df.isnull().sum().to_dict()
missing_dict

{'Unnamed: 0': 0,
 'id': 0,
 'name': 7,
 'age': 11,
 'salary': 12,
 'department': 8,
 'city': 4,
 'rating': 8,
 'experience': 12,
 'status': 17,
 'score': 11}

In [13]:
df.rating.describe().to_dict()

{'count': 42.0,
 'mean': 2.880952380952381,
 'std': 1.4176996302389158,
 'min': 1.0,
 '25%': 1.0,
 '50%': 3.0,
 '75%': 4.0,
 'max': 5.0}

In [19]:
df.select_dtypes(include=['number']).corr()

                  id       age    salary    rating  experience     score
id          1.000000  0.135425  0.261187 -0.106424    0.037055 -0.219842
age         0.135425  1.000000  0.412000 -0.214029   -0.441966  0.022272
salary      0.261187  0.412000  1.000000  0.321812   -0.258106  0.045017
rating     -0.106424 -0.214029  0.321812  1.000000   -0.021668  0.108841
experience  0.037055 -0.441966 -0.258106 -0.021668    1.000000 -0.068051
score      -0.219842  0.022272  0.045017  0.108841   -0.068051  1.000000

In [21]:
df.memory_usage()

Index         132
id            400
name          400
age           400
salary        400
department    400
city          400
rating        400
experience    400
status        400
score         400
dtype: int64

In [29]:
data=df.groupby(['name','city'])[['salary','department']].sum().to_dict()
data

{'salary': {('Alice', 'Bangalore'): 175000.0,
  ('Alice', 'Delhi'): 0.0,
  ('Alice', 'Pune'): 45000.0,
  ('Bob', 'Bangalore'): 0.0,
  ('Bob', 'Delhi'): 205000.0,
  ('Bob', 'Pune'): 90000.0,
  ('Charlie', 'Bangalore'): 90000.0,
  ('Charlie', 'Delhi'): 45000.0,
  ('Charlie', 'Mumbai'): 120000.0,
  ('Charlie', 'Pune'): 65000.0,
  ('David', 'Bangalore'): 195000.0,
  ('David', 'Delhi'): 150000.0,
  ('David', 'Mumbai'): 65000.0,
  ('David', 'Pune'): 0.0,
  ('Eva', 'Bangalore'): 130000.0,
  ('Eva', 'Delhi'): 120000.0,
  ('Eva', 'Mumbai'): 120000.0,
  ('Eva', 'Pune'): 0.0},
 'department': {('Alice', 'Bangalore'): 'FinanceHRSales',
  ('Alice', 'Delhi'): 'Finance',
  ('Alice', 'Pune'): 'Finance',
  ('Bob', 'Bangalore'): 'HR',
  ('Bob', 'Delhi'): 'ITFinanceIT',
  ('Bob', 'Pune'): 'HRFinance',
  ('Charlie', 'Bangalore'): 'FinanceSales',
  ('Charlie', 'Delhi'): 'Sales',
  ('Charlie', 'Mumbai'): 'HRHRFinance',
  ('Charlie', 'Pune'): '',
  ('David', 'Bangalore'): 'FinanceSalesHR',
  ('David', 'Delhi'): 'HRHR',
  ('David', 'Mumbai'): 'HR',
  ('David', 'Pune'): 'HRITIT',
  ('Eva', 'Bangalore'): 'SalesHR',
  ('Eva', 'Delhi'): 'ITIT',
  ('Eva', 'Mumbai'): 'FinanceHR',
  ('Eva', 'Pune'): 'Sales'}}

In [30]:
data_dd = pd.DataFrame(data)
data_dd

                     salary      department
Alice   Bangalore  175000.0  FinanceHRSales
        Delhi           0.0         Finance
        Pune        45000.0         Finance
Bob     Bangalore       0.0              HR
        Delhi      205000.0     ITFinanceIT
        Pune        90000.0       HRFinance
Charlie Bangalore   90000.0    FinanceSales
        Delhi       45000.0           Sales
        Mumbai     120000.0     HRHRFinance
        Pune        65000.0
David   Bangalore  195000.0  FinanceSalesHR
        Delhi      150000.0            HRHR
        Mumbai      65000.0              HR
        Pune            0.0          HRITIT
Eva     Bangalore  130000.0         SalesHR
        Delhi      120000.0            ITIT
        Mumbai     120000.0       FinanceHR
        Pune            0.0           Sales

In [5]:
df.select_dtypes(include=['number']).describe().to_dict()

{'id': {'count': 50.0,
  'mean': 24.4,
  'std': 15.433861526936578,
  'min': 1.0,
  '25%': 10.5,
  '50%': 24.5,
  '75%': 37.75,
  'max': 50.0},
 'age': {'count': 39.0,
  'mean': 28.846153846153847,
  'std': 4.614271120741444,
  'min': 22.0,
  '25%': 25.0,
  '50%': 31.0,
  '75%': 31.0,
  'max': 35.0},
 'salary': {'count': 38.0,
  'mean': 59210.52631578947,
  'std': 11998.103216616619,
  'min': 45000.0,
  '25%': 45000.0,
  '50%': 65000.0,
  '75%': 65000.0,
  'max': 75000.0},
 'rating': {'count': 42.0,
  'mean': 2.880952380952381,
  'std': 1.4176996302389158,
  'min': 1.0,
  '25%': 1.0,
  '50%': 3.0,
  '75%': 4.0,
  'max': 5.0},
 'experience': {'count': 38.0,
  'mean': 5.7894736842105265,
  'std': 3.264534193309784,
  'min': 1.0,
  '25%': 3.5,
  '50%': 5.0,
  '75%': 9.25,
  'max': 10.0},
 'score': {'count': 39.0,
  'mean': 77.03076923076922,
  'std': 13.406855156306653,
  'min': 55.5,
  '25%': 67.8,
  '50%': 72.1,
  '75%': 88.4,
  'max': 91.2}}

In [22]:
df.dtypes

id              int64
name              str
age           float64
salary        float64
department        str
city              str
rating        float64
experience    float64
status            str
score         float64
dtype: object

In [25]:
schema = {
    "id":{
        "dtype": str,
        "nullable": True
    }
}

In [26]:
import pandas as pd
import numpy as np

def validate_schema(df, schema):
    valid = True
    errors = {}

    for col, constraints in schema.items():
        # 1. Check if column exists
        if col not in df.columns:
            errors[col] = "Column not found"
            valid = False
            continue

        # 2. Check for null values
        if not constraints.get("nullable", True):
            null_count = df[col].isnull().sum()
            if null_count > 0:
                errors[col] = f"Contains {null_count} null values"
                valid = False
                continue

        # 3. Check data types
        expected_dtype = constraints["dtype"]
        actual_dtype = df[col].dtype

        # Simplified type checking
        if not np.issubdtype(actual_dtype, expected_dtype):
            errors[col] = f"Expected {expected_dtype.__name__}, found {actual_dtype}"
            valid = False

        # 4. Check for non-numeric values (if expecting numeric)
        if expected_dtype in [int, float, np.number]:
            if not pd.api.types.is_numeric_dtype(df[col]):
                errors[col] = "Contains non-numeric values"
                valid = False

    return {"valid": valid, "errors": errors}

print(validate_schema(df,schema=schema))

{'valid': False, 'errors': {'id': 'Expected str, found int64'}}

In [32]:
import logging

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s - %(levelname)s - %(message)s"
)

logger = logging.getLogger("DataManager")
logger.info("Running...")

2026-06-02 17:49:27,093 - INFO - Running...

In [33]:
logging.info("Loaded CSV")
logging.warning("Missing values detected")
logging.error("File not found")

2026-06-02 17:49:29,788 - INFO - Loaded CSV
2026-06-02 17:49:29,788 - WARNING - Missing values detected
2026-06-02 17:49:29,790 - ERROR - File not found

In [34]:
logger.critical("Database connection lost")

2026-06-02 17:49:30,813 - CRITICAL - Database connection lost

In [3]:
import pandas as pd
dd = pd.DataFrame({
    "id": [1, 1, 2]
})
dd.drop_duplicates(inplace=True)
len(dd)

2